model = "gpt-5.4"
model_reasoning_effort = "high"
notify = [
  "godotenv",
  "-f",
  "/Users/me/.env.secret",
  "agent",
  "codex",
  "notify",
]

[notice.model_migrations]
"gpt-5.2-codex" = "gpt-5.3-codex"
"gpt-5.3-codex" = "gpt-5.4"

[projects."/Users/me/codex"]
trust_level = "trusted"

[projects."/Users/me/github.com/hayeah/dotfiles"]
trust_level = "trusted"

[projects."/Users/me/github.com/hayeah/devportv2"]
trust_level = "trusted"

[projects."/Users/me/github.com/hayeah/agentproxy"]
trust_level = "trusted"

[projects."/Users/me/github.com/hayeah/vision-manga-reader"]
trust_level = "trusted"

[projects."/Users/me/magicpath/epub-reader-orange"]
trust_level = "trusted"

[projects."/Users/me/github.com/hayeah/epubdown"]
trust_level = "trusted"

[projects."/Users/me/github.com/hayeah/manga"]
trust_level = "trusted"

[projects."/Users/me/github.com/hayeah/iosfun"]
trust_level = "trusted"

[projects."/Users/me/github.com/hayeah/go-lstree"]
trust_level = "trusted"

[projects."/Users/me/Dropbox/notes/2026-04-08/tmp/144454.710-codex-watcher-smoke"]
trust_level = "trusted"

[plugins."github@openai-curated"]
enabled = true
